title:              Jiun's Blog
email:              wjdwldns04@naver.com
description:        개발 공부하는 ENFJ 공대생
author:             Jiun Jung
baseurl:            ""
url:                "https://JiunJung.github.io"

# Social Profiles
twitter_username:   
github_username:    JiunJung
facebook_username:  
instagram_username:  jiiiun_jung
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-JSJ2FBLSN4 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
